import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Payload, not hand-written:
    "src/app/(payload)/admin/importMap.js",
    "src/payload/payload-types.ts",
    "src/migrations/**",
    // Decoder Draco vendor, disalin apa adanya dari
    // node_modules/three/examples/jsm/libs/draco/gltf/, bukan kode tulisan tangan:
    "public/draco/**",
    // Bundel sementara bun run seed dan bun run migrate, lihat komentar di
    // package.json, scripts/seed.ts, dan scripts/migrate.ts. Ditulis ulang
    // tiap run, bukan kode tulisan tangan.
    ".seed-bundle.js",
    ".migrate-bundle.js",
  ]),
]);

export default eslintConfig;
