/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    inquiries: Inquiry;
    posts: Post;
    categories: Category;
    clients: Client;
    certifications: Certification;
    'business-lines': BusinessLine;
    vessels: Vessel;
    'fleet-classes': FleetClass;
    'legal-documents': LegalDocument;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'business-lines': BusinessLinesSelect<false> | BusinessLinesSelect<true>;
    vessels: VesselsSelect<false> | VesselsSelect<true>;
    'fleet-classes': FleetClassesSelect<false> | FleetClassesSelect<true>;
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-hero': HomeHero;
    'home-sections': HomeSection;
    'about-page': AboutPage;
    'business-page': BusinessPage;
    'business-subpages': BusinessSubpage;
    'contact-career': ContactCareer;
    appearance: Appearance;
    'articles-page': ArticlesPage;
    'company-profile': CompanyProfile;
    'site-navigation': SiteNavigation;
  };
  globalsSelect: {
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'home-sections': HomeSectionsSelect<false> | HomeSectionsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'business-page': BusinessPageSelect<false> | BusinessPageSelect<true>;
    'business-subpages': BusinessSubpagesSelect<false> | BusinessSubpagesSelect<true>;
    'contact-career': ContactCareerSelect<false> | ContactCareerSelect<true>;
    appearance: AppearanceSelect<false> | AppearanceSelect<true>;
    'articles-page': ArticlesPageSelect<false> | ArticlesPageSelect<true>;
    'company-profile': CompanyProfileSelect<false> | CompanyProfileSelect<true>;
    'site-navigation': SiteNavigationSelect<false> | SiteNavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Akun yang bisa login ke /admin. Nama dipakai sebagai penulis artikel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nama yang tampil sebagai penulis artikel.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Semua gambar yang diunggah lewat admin (cover artikel, logo klien, badge sertifikasi). Disimpan di Vercel Blob, bukan di repo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text bahasa Indonesia, wajib diisi.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Lead yang masuk dari form /kontak dan /bisnis/transportasi-bbm/permintaan-informasi. Hanya untuk dibaca — jangan buat entri manual di sini.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  company?: string | null;
  phone: string;
  email: string;
  service?: string | null;
  message: string;
  source: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Artikel di halaman /artikel dan blok "Artikel terbaru" di Beranda. Status Published wajib supaya tampil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Terisi otomatis dari judul. Mengubahnya setelah artikel terbit membuat alamat lama mati.
   */
  slug: string;
  /**
   * Dipakai sebagai meta description dan ringkasan di kartu.
   */
  excerpt: string;
  coverImage: number | Media;
  content: (
    | {
        text: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heading';
      }
    | {
        text: string;
        attribution?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
  )[];
  /**
   * Dihitung otomatis dari panjang isi saat disimpan.
   */
  readingMinutes?: number | null;
  category: number | Category;
  publishedAt: string;
  author: number | User;
  /**
   * Pilihan manual artikel terkait. Kosongkan untuk memakai kategori sama + terbaru secara otomatis.
   */
  relatedOverride?: (number | Post)[] | null;
  seo?: {
    /**
     * Opsional. Kosong berarti memakai judul artikel.
     */
    metaTitle?: string | null;
    /**
     * Opsional. Kosong berarti memakai excerpt.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Kategori filter di /artikel. Namanya juga tampil di tiap kartu artikel dan halaman detail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Terisi otomatis dari nama.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logo klien di marquee halaman /bisnis. Urutan diatur field order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  sector: string;
  /**
   * Kosongkan untuk merender nama klien sebagai teks (belum ada logo resmi).
   */
  logo?: (number | null) | Media;
  source: 'cp-pdf' | 'riset-publik' | 'belum-terverifikasi';
  /**
   * Angka lebih kecil tampil lebih dulu di marquee.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Badge sertifikasi (ISO 9001, ISM Code, HSSE) di blok sertifikasi Beranda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  name: string;
  badge: number | Media;
  alt: string;
  source: 'cp-pdf' | 'riset-publik' | 'belum-terverifikasi';
  /**
   * Angka lebih kecil tampil lebih dulu di hero.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lini bisnis utama dan afiliasi. Tampil di Beranda dan halaman /bisnis, plus dipakai /bisnis/transportasi-bbm & /bisnis/penumpang-roro. Field "kind" memisahkan Lini utama vs Afiliasi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-lines".
 */
export interface BusinessLine {
  id: number;
  /**
   * Terisi otomatis dari judul. Dipakai kode untuk mencari entri ini.
   */
  slug: string;
  kind: 'lini-utama' | 'afiliasi';
  /**
   * Contoh: "01".
   */
  number: string;
  title: string;
  operator: string;
  summary: string;
  bullets: string[];
  /**
   * Kosongkan kedua field untuk lini tanpa metrik (afiliasi).
   */
  metric?: {
    value?: string | null;
    label?: string | null;
  };
  /**
   * ID aset di src/lib/media/manifest.ts (pipeline gambar statis). Kosongkan kalau lini ini tidak punya foto.
   */
  mediaId?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Daftar kapal per kelas. Tidak tampil satu per satu di situs, tapi jumlahnya per kelas muncul di Beranda dan halaman /bisnis/*. classSlug harus cocok dengan slug di Fleet Classes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vessels".
 */
export interface Vessel {
  id: number;
  name: string;
  classSlug: string;
  /**
   * Hanya diisi untuk kapal ro-ro-ferry.
   */
  routeId?: string | null;
  source: 'cp-pdf' | 'riset-publik' | 'belum-terverifikasi';
  updatedAt: string;
  createdAt: string;
}
/**
 * 5 kelas kapal di komparator 3D Beranda dan di halaman /bisnis/transportasi-bbm & /bisnis/penumpang-roro. Jumlah kapal per kelas dihitung otomatis dari koleksi Vessels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-classes".
 */
export interface FleetClass {
  id: number;
  slug: string;
  name: string;
  category: string;
  lengthMeters: number;
  beamMeters: number;
  /**
   * Kosongkan untuk kelas tanpa DWT, misalnya Ro-Ro Ferry.
   */
  dwt?: number | null;
  capacityLabel: string;
  /**
   * Hanya diisi untuk kelas penumpang.
   */
  passengerCapacity?: number | null;
  altText: string;
  /**
   * Urutan tampil di comparator 3D dan blueprint.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tabel dokumen legal dan perizinan di halaman /tentang-kami.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  document: string;
  number: string;
  issuer: string;
  source: 'cp-pdf' | 'riset-publik' | 'belum-terverifikasi';
  /**
   * Angka lebih kecil tampil lebih dulu di kelompoknya.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'business-lines';
        value: number | BusinessLine;
      } | null)
    | ({
        relationTo: 'vessels';
        value: number | Vessel;
      } | null)
    | ({
        relationTo: 'fleet-classes';
        value: number | FleetClass;
      } | null)
    | ({
        relationTo: 'legal-documents';
        value: number | LegalDocument;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  phone?: T;
  email?: T;
  service?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  content?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              attribution?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  readingMinutes?: T;
  category?: T;
  publishedAt?: T;
  author?: T;
  relatedOverride?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  sector?: T;
  logo?: T;
  source?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  badge?: T;
  alt?: T;
  source?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-lines_select".
 */
export interface BusinessLinesSelect<T extends boolean = true> {
  slug?: T;
  kind?: T;
  number?: T;
  title?: T;
  operator?: T;
  summary?: T;
  bullets?: T;
  metric?:
    | T
    | {
        value?: T;
        label?: T;
      };
  mediaId?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vessels_select".
 */
export interface VesselsSelect<T extends boolean = true> {
  name?: T;
  classSlug?: T;
  routeId?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-classes_select".
 */
export interface FleetClassesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  category?: T;
  lengthMeters?: T;
  beamMeters?: T;
  dwt?: T;
  capacityLabel?: T;
  passengerCapacity?: T;
  altText?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  document?: T;
  number?: T;
  issuer?: T;
  source?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Teks paling atas Beranda: baris kecil, judul besar, sub-teks, label gulir, dan dua kartu lini bisnis (kiri BBM, kanan Ro-Ro).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  /**
   * Baris kecil huruf kapital di atas judul.
   */
  eyebrow: string;
  /**
   * Judul utama. Usahakan maksimal 7 kata supaya tetap dua baris di layar lebar.
   */
  headline: string;
  /**
   * Satu kalimat di bawah judul. Maksimal sekitar 20 kata.
   */
  subheadline: string;
  /**
   * Kata di indikator gulir bawah, mis. "Gulir".
   */
  scrollLabel: string;
  bbm: {
    label: string;
    /**
     * Angka besar di kartu, mis. jumlah tanker.
     */
    value: number;
    /**
     * Satuan, mis. "Tanker".
     */
    unit: string;
    description: string;
    /**
     * Teks tombol. Tautannya tetap ke halaman permintaan informasi BBM.
     */
    ctaLabel: string;
  };
  roro: {
    label: string;
    value: number;
    unit: string;
    description: string;
    ctaLabel: string;
    /**
     * Tautan tombol Ro-Ro, mis. situs pemesanan tiket.
     */
    ctaHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Judul dan paragraf tiap bagian Beranda di bawah hero: Ship-to-ship, Afiliasi, Perbandingan Armada, Rute Ro-Ro, Sejak 1988, deret angka, dan ajakan penutup.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-sections".
 */
export interface HomeSection {
  id: number;
  dayCut: {
    heading: string;
    body: string;
  };
  affiliates: {
    heading: string;
    subtext: string;
  };
  fleetComparator: {
    heading: string;
    /**
     * Deskripsi versi 3D (layar lebar).
     */
    description: string;
    /**
     * Deskripsi versi sederhana (mobile / hemat gerak).
     */
    descriptionStatic: string;
    /**
     * Mis. "Seret untuk memutar".
     */
    dragHint: string;
    /**
     * Mis. "1 kotak grid = 10 m".
     */
    gridHint: string;
  };
  routeMap: {
    heading: string;
    description: string;
  };
  since1988: {
    heading: string;
    /**
     * Kalimat di bawah angka tahun beroperasi.
     */
    counterCaption: string;
    /**
     * Kalimat pendirian. Tulis lengkap — tidak otomatis ambil dari Company Profile.
     */
    foundingSentence: string;
    genealogyLinkLabel: string;
  };
  /**
   * Label di bawah tiap angka. Angkanya dihitung otomatis.
   */
  stats: {
    shipsLabel: string;
    peopleLabel: string;
    yearsLabel: string;
    portsLabel: string;
    membershipsHeading: string;
  };
  cta: {
    heading: string;
    /**
     * Teks tombol. Tautannya tetap ke /kontak.
     */
    buttonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Semua teks di halaman Tentang Kami: hero, label angka, blok jati diri, nilai inti, struktur grup, legalitas, kantor, dan ajakan penutup.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    title: string;
    intro1: string;
    intro2: string;
  };
  /**
   * Kalimat kecil di bawah tiap angka. Angkanya dihitung otomatis.
   */
  statLabels: {
    years: string;
    ships: string;
    people: string;
    sectors: string;
  };
  /**
   * Bagian di seksi Jati Diri. Isi lead ATAU items, note opsional.
   */
  identity?:
    | {
        title: string;
        /**
         * Paragraf pembuka. Kosongkan kalau memakai items.
         */
        lead?: string | null;
        /**
         * Daftar butir. Kosongkan kalau memakai lead.
         */
        items?: string[] | null;
        /**
         * Catatan kaki kecil, opsional.
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  coreValues: {
    heading: string;
    intro: string;
    /**
     * Teks kecil di bawah medali "DML".
     */
    medallionCaption: string;
  };
  groupChart: {
    heading: string;
    intro: string;
    /**
     * Nama simpul induk di bagan.
     */
    parentName: string;
    parentCaption: string;
  };
  legal: {
    heading: string;
    standardsLabel: string;
    membershipsLabel: string;
    footnote: string;
  };
  offices: {
    heading: string;
    intro: string;
    dmlOwnerLabel: string;
    groupOwnerLabel: string;
  };
  cta: {
    heading: string;
    /**
     * Tombol ke /bisnis.
     */
    primaryButtonLabel: string;
    /**
     * Tombol ke /kontak.
     */
    secondaryButtonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Teks halaman Bisnis Kami: hero, dua panel lini utama, alur ship-to-ship, judul bagian afiliasi & klien, ajakan penutup, dan label indeks samping.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-page".
 */
export interface BusinessPage {
  id: number;
  hero: {
    title: string;
    intro: string;
    metrics?:
      | {
          value: number;
          unit: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  liniUtama?: {
    /**
     * Urutan penting: panel pertama tautannya ke /bisnis/transportasi-bbm, kedua ke /bisnis/penumpang-roro.
     */
    panels?:
      | {
          /**
           * Mis. "01".
           */
          num: string;
          title: string;
          summary: string;
          metric: string;
          metricLabel: string;
          bullets: string[];
          /**
           * Teks tombol.
           */
          cta: string;
          id?: string | null;
        }[]
      | null;
  };
  alurSts: {
    kicker: string;
    heading: string;
    intro: string;
    steps?:
      | {
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  afiliasi: {
    kicker: string;
    heading: string;
    subtext: string;
  };
  klien: {
    kicker: string;
    heading: string;
    /**
     * Satuan angka jumlah klien, mis. "klien".
     */
    stat1Unit: string;
    stat1Caption: string;
    stat2Value: string;
    stat2Unit: string;
    stat2Caption: string;
    /**
     * Catatan kecil di bawah pita logo.
     */
    placeholderNote: string;
  };
  cta: {
    kicker: string;
    heading: string;
    /**
     * Tombol ke halaman permintaan informasi.
     */
    primaryButtonLabel: string;
    /**
     * Tombol ke situs pemesanan tiket.
     */
    secondaryButtonLabel: string;
  };
  /**
   * Lima label navigasi mengambang di sisi kanan. Urutan = urutan bagian.
   */
  sectionIndexLabels: string[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Judul bagian dan paragraf di /bisnis/transportasi-bbm, /bisnis/penumpang-roro, dan halaman form permintaan informasi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-subpages".
 */
export interface BusinessSubpage {
  id: number;
  bbm: {
    eyebrow: string;
    title: string;
    kelasArmadaHeading: string;
    kelasArmadaDesc: string;
    /**
     * Catatan kecil di bawah tabel kelas.
     */
    sumberNote: string;
    daftarKapalHeading: string;
    daftarKapalDesc: string;
    alurHeading: string;
    alurDesc: string;
    steps?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    standarHeading: string;
    /**
     * Teks tombol ke form permintaan informasi.
     */
    ctaLabel: string;
  };
  roro: {
    eyebrow: string;
    title: string;
    lintasanHeading: string;
    lintasanDesc: string;
    armadaHeading: string;
    armadaDesc: string;
    lengthLabel: string;
    lengthUnit: string;
    capacityLabel: string;
    tiketHeading: string;
    tiketDesc: string;
    tiketButtonLabel: string;
  };
  inquiry: {
    title: string;
    intro: string;
    directContactLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Judul dan paragraf di halaman Karier dan halaman Kontak.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-career".
 */
export interface ContactCareer {
  id: number;
  career: {
    title: string;
    /**
     * Kalimat status lowongan.
     */
    noOpeningsText: string;
    spontaneousText: string;
    whatsappButtonLabel: string;
    /**
     * Teks yang otomatis terisi di WhatsApp saat tombol diklik.
     */
    whatsappMessage: string;
  };
  contact: {
    title: string;
    intro: string;
    phoneLabel: string;
    mapsLinkLabel: string;
    perLineHeading: string;
    perLineIntro: string;
    perLineLinkLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Preset warna aksen situs. Hanya warna tautan/tombol/aksen yang berubah — latar dan teks tetap. Scene 3D di Beranda tetap navy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance".
 */
export interface Appearance {
  id: number;
  /**
   * Perubahan langsung terlihat setelah Save.
   */
  theme: 'navy' | 'teal' | 'forest' | 'plum';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Heading dan intro di kepala halaman /artikel, plus daftar kanal share.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles-page".
 */
export interface ArticlesPage {
  id: number;
  heading: string;
  intro: string;
  /**
   * Pita catatan opsional di bawah intro. Kosongkan untuk menyembunyikannya.
   */
  notice?: string | null;
  /**
   * Jumlah kartu per halaman sebelum tombol "Muat lebih banyak" dipakai.
   */
  pageSize: number;
  /**
   * Kosongkan untuk memakai artikel terbit terbaru secara otomatis.
   */
  featured?: (number | null) | Post;
  shareChannels: ('whatsapp' | 'linkedin' | 'x' | 'email' | 'copy')[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Data inti perusahaan: nama, alamat, kantor, nilai, standar, ringkasan armada, struktur grup. Dipakai hampir semua halaman — Beranda, /tentang-kami, /bisnis/*, /kontak, /karier, dan footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-profile".
 */
export interface CompanyProfile {
  id: number;
  legalName: string;
  shortName: string;
  abbreviation: string;
  tagline: string;
  foundedIso: string;
  founder: string;
  parent: string;
  phone: string;
  /**
   * Format E.164 tanpa tanda plus, untuk tautan wa.me.
   */
  whatsapp: string;
  bookingUrl: string;
  offices: {
    label: string;
    street: string;
    city: string;
    postalCode?: string | null;
    province: string;
    phone?: string | null;
    fax?: string | null;
    id?: string | null;
  }[];
  /**
   * Tiga huruf DML sebagai nilai. Urutan baris adalah urutan tampil.
   */
  values: {
    key: 'D' | 'M' | 'L';
    term: string;
    description: string;
    id?: string | null;
  }[];
  standards: {
    label: string;
    items: {
      name: string;
      source: 'cp-pdf' | 'riset-publik' | 'belum-terverifikasi';
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  memberships: {
    name: string;
    /**
     * Kepanjangan akronim, opsional.
     */
    expansion?: string | null;
    id?: string | null;
  }[];
  fleetSummary: {
    vessels: number;
    passengerVessels: number;
    oilTransportVessels: number;
    people: number;
  };
  /**
   * Kantor Sinar Alam Corporation, bukan kantor DML sendiri.
   */
  groupOffices: {
    label: string;
    street: string;
    city: string;
    postalCode?: string | null;
    province: string;
    phone?: string | null;
    fax?: string | null;
    id?: string | null;
  }[];
  /**
   * Peta sektor usaha grup, dipakai halaman Tentang Kami.
   */
  groupUnits: {
    sector: string;
    companies: string[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Menu di header dan grup tautan di footer. Berlaku di semua halaman.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation".
 */
export interface SiteNavigation {
  id: number;
  /**
   * Menu di header, urutan baris adalah urutan tampil.
   */
  navItems: {
    label: string;
    href: string;
    /**
     * Centang kalau tautan keluar dari situs ini.
     */
    external?: boolean | null;
    id?: string | null;
  }[];
  footerGroups: {
    heading: string;
    items: {
      label: string;
      href: string;
      external?: boolean | null;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  subheadline?: T;
  scrollLabel?: T;
  bbm?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        description?: T;
        ctaLabel?: T;
      };
  roro?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-sections_select".
 */
export interface HomeSectionsSelect<T extends boolean = true> {
  dayCut?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  affiliates?:
    | T
    | {
        heading?: T;
        subtext?: T;
      };
  fleetComparator?:
    | T
    | {
        heading?: T;
        description?: T;
        descriptionStatic?: T;
        dragHint?: T;
        gridHint?: T;
      };
  routeMap?:
    | T
    | {
        heading?: T;
        description?: T;
      };
  since1988?:
    | T
    | {
        heading?: T;
        counterCaption?: T;
        foundingSentence?: T;
        genealogyLinkLabel?: T;
      };
  stats?:
    | T
    | {
        shipsLabel?: T;
        peopleLabel?: T;
        yearsLabel?: T;
        portsLabel?: T;
        membershipsHeading?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        intro1?: T;
        intro2?: T;
      };
  statLabels?:
    | T
    | {
        years?: T;
        ships?: T;
        people?: T;
        sectors?: T;
      };
  identity?:
    | T
    | {
        title?: T;
        lead?: T;
        items?: T;
        note?: T;
        id?: T;
      };
  coreValues?:
    | T
    | {
        heading?: T;
        intro?: T;
        medallionCaption?: T;
      };
  groupChart?:
    | T
    | {
        heading?: T;
        intro?: T;
        parentName?: T;
        parentCaption?: T;
      };
  legal?:
    | T
    | {
        heading?: T;
        standardsLabel?: T;
        membershipsLabel?: T;
        footnote?: T;
      };
  offices?:
    | T
    | {
        heading?: T;
        intro?: T;
        dmlOwnerLabel?: T;
        groupOwnerLabel?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        primaryButtonLabel?: T;
        secondaryButtonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-page_select".
 */
export interface BusinessPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        intro?: T;
        metrics?:
          | T
          | {
              value?: T;
              unit?: T;
              label?: T;
              id?: T;
            };
      };
  liniUtama?:
    | T
    | {
        panels?:
          | T
          | {
              num?: T;
              title?: T;
              summary?: T;
              metric?: T;
              metricLabel?: T;
              bullets?: T;
              cta?: T;
              id?: T;
            };
      };
  alurSts?:
    | T
    | {
        kicker?: T;
        heading?: T;
        intro?: T;
        steps?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  afiliasi?:
    | T
    | {
        kicker?: T;
        heading?: T;
        subtext?: T;
      };
  klien?:
    | T
    | {
        kicker?: T;
        heading?: T;
        stat1Unit?: T;
        stat1Caption?: T;
        stat2Value?: T;
        stat2Unit?: T;
        stat2Caption?: T;
        placeholderNote?: T;
      };
  cta?:
    | T
    | {
        kicker?: T;
        heading?: T;
        primaryButtonLabel?: T;
        secondaryButtonLabel?: T;
      };
  sectionIndexLabels?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-subpages_select".
 */
export interface BusinessSubpagesSelect<T extends boolean = true> {
  bbm?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        kelasArmadaHeading?: T;
        kelasArmadaDesc?: T;
        sumberNote?: T;
        daftarKapalHeading?: T;
        daftarKapalDesc?: T;
        alurHeading?: T;
        alurDesc?: T;
        steps?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
        standarHeading?: T;
        ctaLabel?: T;
      };
  roro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lintasanHeading?: T;
        lintasanDesc?: T;
        armadaHeading?: T;
        armadaDesc?: T;
        lengthLabel?: T;
        lengthUnit?: T;
        capacityLabel?: T;
        tiketHeading?: T;
        tiketDesc?: T;
        tiketButtonLabel?: T;
      };
  inquiry?:
    | T
    | {
        title?: T;
        intro?: T;
        directContactLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-career_select".
 */
export interface ContactCareerSelect<T extends boolean = true> {
  career?:
    | T
    | {
        title?: T;
        noOpeningsText?: T;
        spontaneousText?: T;
        whatsappButtonLabel?: T;
        whatsappMessage?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        intro?: T;
        phoneLabel?: T;
        mapsLinkLabel?: T;
        perLineHeading?: T;
        perLineIntro?: T;
        perLineLinkLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance_select".
 */
export interface AppearanceSelect<T extends boolean = true> {
  theme?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles-page_select".
 */
export interface ArticlesPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  notice?: T;
  pageSize?: T;
  featured?: T;
  shareChannels?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-profile_select".
 */
export interface CompanyProfileSelect<T extends boolean = true> {
  legalName?: T;
  shortName?: T;
  abbreviation?: T;
  tagline?: T;
  foundedIso?: T;
  founder?: T;
  parent?: T;
  phone?: T;
  whatsapp?: T;
  bookingUrl?: T;
  offices?:
    | T
    | {
        label?: T;
        street?: T;
        city?: T;
        postalCode?: T;
        province?: T;
        phone?: T;
        fax?: T;
        id?: T;
      };
  values?:
    | T
    | {
        key?: T;
        term?: T;
        description?: T;
        id?: T;
      };
  standards?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              name?: T;
              source?: T;
              id?: T;
            };
        id?: T;
      };
  memberships?:
    | T
    | {
        name?: T;
        expansion?: T;
        id?: T;
      };
  fleetSummary?:
    | T
    | {
        vessels?: T;
        passengerVessels?: T;
        oilTransportVessels?: T;
        people?: T;
      };
  groupOffices?:
    | T
    | {
        label?: T;
        street?: T;
        city?: T;
        postalCode?: T;
        province?: T;
        phone?: T;
        fax?: T;
        id?: T;
      };
  groupUnits?:
    | T
    | {
        sector?: T;
        companies?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-navigation_select".
 */
export interface SiteNavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  footerGroups?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}